from pydantic import BaseModel
from typing import List, Optional
from sqlalchemy import Column, Integer, ForeignKey, UniqueConstraint
from sqlalchemy.orm import relationship
from database import Base

class Book(BaseModel):
    id: int
    title: str
    price: float
    image: str
    description: str
    author: str
    category: str
    rating: float
    review_count: int
    publisher: str
    published_date: str
    language: str
    page_count: int
    isbn: str
    vendor: str
    special_offer: bool
    stock_status: str
    offer: bool = False
    discount: Optional[int] = 0
    top_of_week: bool = False

BOOKS: List[Book] = [
    Book(
        id=1,
        title="The Kite Runner",
        price=39.99,
        image="https://example.com/the_kite_runner.jpg",
        description="A gripping and emotional story of friendship and redemption...",
        author="Khaled Hosseini",
        category="Novels",
        rating=4.5,
        review_count=1245,
        publisher="Riverhead Books",
        published_date="2003-05-29",
        language="en",
        page_count=371,
        isbn="9781594631931",
        vendor="GoodDay",
        special_offer=True,
        stock_status="In Stock",
        offer=True,
        discount=20,
        top_of_week=True
    ),
    # 19 more books with varied data
    Book(
        id=2,
        title="A Brief History of Time",
        price=29.99,
        image="https://example.com/brief_history_of_time.jpg",
        description="Stephen Hawking's classic work on cosmology...",
        author="Stephen Hawking",
        category="Science",
        rating=4.7,
        review_count=2100,
        publisher="Bantam Books",
        published_date="1988-04-01",
        language="en",
        page_count=256,
        isbn="9780553380163",
        vendor="BookWorld",
        special_offer=False,
        stock_status="In Stock",
        offer=True,
        discount=15,
        top_of_week=True
    ),
    Book(
        id=3,
        title="Sapiens: A Brief History of Humankind",
        price=34.99,
        image="https://example.com/sapiens.jpg",
        description="Yuval Noah Harari explores the history and impact of Homo sapiens...",
        author="Yuval Noah Harari",
        category="History",
        rating=4.6,
        review_count=1800,
        publisher="Harper",
        published_date="2011-01-01",
        language="en",
        page_count=443,
        isbn="9780062316097",
        vendor="ReadMore",
        special_offer=True,
        stock_status="In Stock"
    ),
    Book(
        id=4,
        title="The Hobbit",
        price=24.99,
        image="https://example.com/the_hobbit.jpg",
        description="J.R.R. Tolkien's fantasy classic...",
        author="J.R.R. Tolkien",
        category="Fantasy",
        rating=4.8,
        review_count=3200,
        publisher="George Allen & Unwin",
        published_date="1937-09-21",
        language="en",
        page_count=310,
        isbn="9780547928227",
        vendor="BookWorld",
        special_offer=False,
        stock_status="In Stock",
        offer=True,
        discount=30,
        top_of_week=True
    ),
    Book(
        id=5,
        title="To Kill a Mockingbird",
        price=19.99,
        image="https://example.com/to_kill_a_mockingbird.jpg",
        description="Harper Lee's Pulitzer Prize-winning novel...",
        author="Harper Lee",
        category="Novels",
        rating=4.9,
        review_count=4100,
        publisher="J.B. Lippincott & Co.",
        published_date="1960-07-11",
        language="en",
        page_count=281,
        isbn="9780061120084",
        vendor="GoodDay",
        special_offer=True,
        stock_status="In Stock",
        top_of_week=True
    ),
    Book(
        id=6,
        title="The Selfish Gene",
        price=27.99,
        image="https://example.com/the_selfish_gene.jpg",
        description="Richard Dawkins' influential book on evolution...",
        author="Richard Dawkins",
        category="Science",
        rating=4.4,
        review_count=950,
        publisher="Oxford University Press",
        published_date="1976-03-13",
        language="en",
        page_count=360,
        isbn="9780199291151",
        vendor="ReadMore",
        special_offer=False,
        stock_status="In Stock"
    ),
    Book(
        id=7,
        title="Steve Jobs",
        price=32.99,
        image="https://example.com/steve_jobs.jpg",
        description="Walter Isaacson's biography of Steve Jobs...",
        author="Walter Isaacson",
        category="Biography",
        rating=4.3,
        review_count=1200,
        publisher="Simon & Schuster",
        published_date="2011-10-24",
        language="en",
        page_count=656,
        isbn="9781451648539",
        vendor="BookWorld",
        special_offer=True,
        stock_status="In Stock"
    ),
    Book(
        id=8,
        title="1984",
        price=22.99,
        image="https://example.com/1984.jpg",
        description="George Orwell's dystopian masterpiece...",
        author="George Orwell",
        category="Novels",
        rating=4.7,
        review_count=5000,
        publisher="Secker & Warburg",
        published_date="1949-06-08",
        language="en",
        page_count=328,
        isbn="9780451524935",
        vendor="GoodDay",
        special_offer=False,
        stock_status="In Stock"
    ),
    Book(
        id=9,
        title="The Alchemist",
        price=18.99,
        image="https://example.com/the_alchemist.jpg",
        description="Paulo Coelho's philosophical novel...",
        author="Paulo Coelho",
        category="Novels",
        rating=4.2,
        review_count=2300,
        publisher="HarperTorch",
        published_date="1988-05-01",
        language="en",
        page_count=208,
        isbn="9780061122415",
        vendor="ReadMore",
        special_offer=True,
        stock_status="In Stock",
        offer=True,
        discount=25
    ),
    Book(
        id=10,
        title="The Great Gatsby",
        price=21.99,
        image="https://example.com/the_great_gatsby.jpg",
        description="F. Scott Fitzgerald's classic novel...",
        author="F. Scott Fitzgerald",
        category="Novels",
        rating=4.4,
        review_count=3100,
        publisher="Charles Scribner's Sons",
        published_date="1925-04-10",
        language="en",
        page_count=180,
        isbn="9780743273565",
        vendor="BookWorld",
        special_offer=False,
        stock_status="In Stock"
    ),
    Book(
        id=11,
        title="Thinking, Fast and Slow",
        price=28.99,
        image="https://example.com/thinking_fast_and_slow.jpg",
        description="Daniel Kahneman's groundbreaking work on human decision-making...",
        author="Daniel Kahneman",
        category="Science",
        rating=4.5,
        review_count=1700,
        publisher="Farrar, Straus and Giroux",
        published_date="2011-10-25",
        language="en",
        page_count=499,
        isbn="9780374533557",
        vendor="GoodDay",
        special_offer=True,
        stock_status="In Stock",
        top_of_week=True
    ),
    Book(
        id=12,
        title="Educated",
        price=26.99,
        image="https://example.com/educated.jpg",
        description="Tara Westover's memoir of resilience and self-invention...",
        author="Tara Westover",
        category="Biography",
        rating=4.6,
        review_count=1400,
        publisher="Random House",
        published_date="2018-02-20",
        language="en",
        page_count=334,
        isbn="9780399590504",
        vendor="ReadMore",
        special_offer=False,
        stock_status="In Stock",
        offer=True,
        discount=30
    ),
    Book(
        id=13,
        title="Brave New World",
        price=23.99,
        image="https://example.com/brave_new_world.jpg",
        description="Aldous Huxley's vision of a dystopian future...",
        author="Aldous Huxley",
        category="Novels",
        rating=4.3,
        review_count=2100,
        publisher="Chatto & Windus",
        published_date="1932-08-18",
        language="en",
        page_count=311,
        isbn="9780060850524",
        vendor="BookWorld",
        special_offer=True,
        stock_status="In Stock"
    ),
    Book(
        id=14,
        title="The Catcher in the Rye",
        price=20.99,
        image="https://example.com/the_catcher_in_the_rye.jpg",
        description="J.D. Salinger's classic coming-of-age novel...",
        author="J.D. Salinger",
        category="Novels",
        rating=4.1,
        review_count=2700,
        publisher="Little, Brown and Company",
        published_date="1951-07-16",
        language="en",
        page_count=214,
        isbn="9780316769488",
        vendor="GoodDay",
        special_offer=False,
        stock_status="In Stock"
    ),
    Book(
        id=15,
        title="The Power of Habit",
        price=25.99,
        image="https://example.com/the_power_of_habit.jpg",
        description="Charles Duhigg explores the science of habit formation...",
        author="Charles Duhigg",
        category="Science",
        rating=4.2,
        review_count=1100,
        publisher="Random House",
        published_date="2012-02-28",
        language="en",
        page_count=371,
        isbn="9780812981605",
        vendor="ReadMore",
        special_offer=True,
        stock_status="In Stock"
    ),
    Book(
        id=16,
        title="The Diary of a Young Girl",
        price=17.99,
        image="https://example.com/diary_of_a_young_girl.jpg",
        description="Anne Frank's poignant diary from World War II...",
        author="Anne Frank",
        category="Biography",
        rating=4.8,
        review_count=3500,
        publisher="Contact Publishing",
        published_date="1947-06-25",
        language="en",
        page_count=283,
        isbn="9780553296983",
        vendor="BookWorld",
        special_offer=False,
        stock_status="In Stock"
    ),
    Book(
        id=17,
        title="The Lord of the Rings",
        price=49.99,
        image="https://example.com/lord_of_the_rings.jpg",
        description="J.R.R. Tolkien's epic fantasy trilogy...",
        author="J.R.R. Tolkien",
        category="Fantasy",
        rating=4.9,
        review_count=6000,
        publisher="George Allen & Unwin",
        published_date="1954-07-29",
        language="en",
        page_count=1178,
        isbn="9780618640157",
        vendor="GoodDay",
        special_offer=True,
        stock_status="In Stock",
        top_of_week=True
    ),
    Book(
        id=18,
        title="The Subtle Art of Not Giving a F*ck",
        price=24.99,
        image="https://example.com/subtle_art.jpg",
        description="Mark Manson's self-help bestseller...",
        author="Mark Manson",
        category="Science",
        rating=4.0,
        review_count=900,
        publisher="HarperOne",
        published_date="2016-09-13",
        language="en",
        page_count=224,
        isbn="9780062457714",
        vendor="ReadMore",
        special_offer=False,
        stock_status="In Stock"
    ),
    Book(
        id=19,
        title="The Book Thief",
        price=22.99,
        image="https://example.com/the_book_thief.jpg",
        description="Markus Zusak's novel set in Nazi Germany...",
        author="Markus Zusak",
        category="Novels",
        rating=4.5,
        review_count=2800,
        publisher="Picador",
        published_date="2005-03-14",
        language="en",
        page_count=552,
        isbn="9780375842207",
        vendor="BookWorld",
        special_offer=True,
        stock_status="In Stock",
        offer=True,
        discount=20
    ),
    Book(
        id=20,
        title="Becoming",
        price=29.99,
        image="https://example.com/becoming.jpg",
        description="Michelle Obama's inspiring memoir...",
        author="Michelle Obama",
        category="Biography",
        rating=4.7,
        review_count=2000,
        publisher="Crown Publishing Group",
        published_date="2018-11-13",
        language="en",
        page_count=448,
        isbn="9781524763138",
        vendor="GoodDay",
        special_offer=True,
        stock_status="In Stock",
        top_of_week=True
    )
] 