"""Add cart and wishlist tables

Revision ID: bc98687a8ccb
Revises: fcc47b52d86c
Create Date: 2025-07-05 16:06:50.339724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc98687a8ccb'
down_revision: Union[str, Sequence[str], None] = 'fcc47b52d86c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
